### ISSUE TITLE
Improve css

### ISSUE THREAD

**Issue by DarkenSoda** [DarkenSoda/task-manager-website#1]
Improve the page visuals

**Comment by pulkitxm** [comment]
Can I get assigned  ?

**Comment by DarkenSoda** [comment]
@Pulkitxm Sure Here you go

**Comment by DarkenSoda** [comment]
@Pulkitxm Good Job! I really like the new visuals

**Comment by pulkitxm** [comment]
Sure Thanks @DarkenSoda
