### ISSUE TITLE
Add a way to undo completed Tasks

### ISSUE THREAD

**Issue by DarkenSoda** [DarkenSoda/task-manager-website#3]
Right now Completed Tasks can't be changed back to uncompleted!
Add a button in the Edit mode to uncomplete a task.

or maybe:

Add a checkbox before each task that shows if it's completed or not.

Note: completed task needs to be moved to the bottom of the list

**Comment by ansarisaqlain987** [comment]
Hi @DarkenSoda I want to contribute to this repository. Please assign me this issue.

**Comment by DarkenSoda** [comment]
> Hi @DarkenSoda I want to contribute to this repository. Please assign me this issue.

Done :). Good luck

**Comment by senaa07** [comment]
Hi @DarkenSoda I want to work on this. Please assign me this issue I can give you a proper solution for this.

**Comment by DarkenSoda** [comment]
> Hi @DarkenSoda I want to work on this. Please assign me this issue I can give you a proper solution for this.

@X-sena-X Done! Do your best :)

**Comment by senaa07** [comment]
I am done with uncomplete button . working on to move the completed task to  bottom.

**Comment by senaa07** [comment]
I have done everything that was asked

**Comment by DarkenSoda** [comment]
@X-sena-X I have reviewed your code, and you've done a great job!
your code works as I wanted exactly :)

but there's little bug now that I'm trying to figure out.

Right now, task IDs are added by checking the last task's id and incrementing it.
having completed tasks go to the bottom may result in duplicate ids, which may result in unwanted behaviour. :(

**Comment by senaa07** [comment]
ohh wait i will give a solution for it

**Comment by DarkenSoda** [comment]
I'm already on it now,
I'll simply create a forloop to calculate the max id so that any new id increment it

**Comment by senaa07** [comment]
No i have completed it. Wait let me push it.

**Comment by senaa07** [comment]
pushed it check it now. Thanks

**Comment by senaa07** [comment]
If u find any more bugs report to it here.

**Comment by DarkenSoda** [comment]
Perfect, I also added a sort function to sort tasks after each add and uncomplete.
that way if you uncomplete something at the bottom it's ordered back to a valid place.

**Comment by DarkenSoda** [comment]
Thanks for your contribution!

I was struggling with moving tasks to last but you made it simple and easy to understand.
This Issue is now closed!

Have a nice day!

**Comment by senaa07** [comment]
thanks! This was my first contribution.
